use crate::constants::{COLOR_FOREGROUND, COLOR_SUCCESS};
use godot::classes::{BoxContainer, Control, IControl, InputEvent};
use godot::prelude::*;
use once_cell::unsync::Lazy;
use phf::phf_map;
use std::collections::HashMap;
use std::f32::consts::PI;

struct Key {
    name: &'static str,
    x_offset: f32,
    width: f32,
    height: f32,
}

// Keymap generated by chatGPT 4
const KEYMAP: Lazy<[Vec<Key>; 6]> = Lazy::new(|| {
    [
        // Function row
        vec![
            Key {
                name: "ESC",
                x_offset: 0.0,
                width: 1.0,
                height: 1.0,
            },
            Key {
                name: "F1",
                x_offset: 2.0,
                width: 1.0,
                height: 1.0,
            },
            Key {
                name: "F2",
                x_offset: 3.0,
                width: 1.0,
                height: 1.0,
            },
            Key {
                name: "F3",
                x_offset: 4.0,
                width: 1.0,
                height: 1.0,
            },
            Key {
                name: "F4",
                x_offset: 5.0,
                width: 1.0,
                height: 1.0,
            },
            Key {
                name: "F5",
                x_offset: 6.5,
                width: 1.0,
                height: 1.0,
            },
            Key {
                name: "F6",
                x_offset: 7.5,
                width: 1.0,
                height: 1.0,
            },
            Key {
                name: "F7",
                x_offset: 8.5,
                width: 1.0,
                height: 1.0,
            },
            Key {
                name: "F8",
                x_offset: 9.5,
                width: 1.0,
                height: 1.0,
            },
            Key {
                name: "F9",
                x_offset: 11.0,
                width: 1.0,
                height: 1.0,
            },
            Key {
                name: "F10",
                x_offset: 12.0,
                width: 1.0,
                height: 1.0,
            },
            Key {
                name: "F11",
                x_offset: 13.0,
                width: 1.0,
                height: 1.0,
            },
            Key {
                name: "F12",
                x_offset: 14.0,
                width: 1.0,
                height: 1.0,
            },
            Key {
                name: "PRINT_SCREEN",
                x_offset: 15.5,
                width: 1.0,
                height: 1.0,
            },
            Key {
                name: "SCROLL_LOCK",
                x_offset: 16.5,
                width: 1.0,
                height: 1.0,
            },
            Key {
                name: "PAUSE",
                x_offset: 17.5,
                width: 1.0,
                height: 1.0,
            },
        ],
        // Numbers row, first row of nav cluster, first row of numpad
        vec![
            Key {
                name: "BACKQUOTE",
                x_offset: 0.0,
                width: 1.0,
                height: 1.0,
            },
            Key {
                name: "1",
                x_offset: 1.0,
                width: 1.0,
                height: 1.0,
            },
            Key {
                name: "2",
                x_offset: 2.0,
                width: 1.0,
                height: 1.0,
            },
            Key {
                name: "3",
                x_offset: 3.0,
                width: 1.0,
                height: 1.0,
            },
            Key {
                name: "4",
                x_offset: 4.0,
                width: 1.0,
                height: 1.0,
            },
            Key {
                name: "5",
                x_offset: 5.0,
                width: 1.0,
                height: 1.0,
            },
            Key {
                name: "6",
                x_offset: 6.0,
                width: 1.0,
                height: 1.0,
            },
            Key {
                name: "7",
                x_offset: 7.0,
                width: 1.0,
                height: 1.0,
            },
            Key {
                name: "8",
                x_offset: 8.0,
                width: 1.0,
                height: 1.0,
            },
            Key {
                name: "9",
                x_offset: 9.0,
                width: 1.0,
                height: 1.0,
            },
            Key {
                name: "0",
                x_offset: 10.0,
                width: 1.0,
                height: 1.0,
            },
            Key {
                name: "MINUS",
                x_offset: 11.0,
                width: 1.0,
                height: 1.0,
            },
            Key {
                name: "EQUAL",
                x_offset: 12.0,
                width: 1.0,
                height: 1.0,
            },
            Key {
                name: "BACKSPACE",
                x_offset: 13.0,
                width: 2.0,
                height: 1.0,
            },
            Key {
                name: "INSERT",
                x_offset: 15.5,
                width: 1.0,
                height: 1.0,
            },
            Key {
                name: "HOME",
                x_offset: 16.5,
                width: 1.0,
                height: 1.0,
            },
            Key {
                name: "PAGE_UP",
                x_offset: 17.5,
                width: 1.0,
                height: 1.0,
            },
            Key {
                name: "NUM_LOCK",
                x_offset: 19.0,
                width: 1.0,
                height: 1.0,
            },
            Key {
                name: "NUM_SLASH",
                x_offset: 20.0,
                width: 1.0,
                height: 1.0,
            },
            Key {
                name: "NUM_ASTERISK",
                x_offset: 21.0,
                width: 1.0,
                height: 1.0,
            },
            Key {
                name: "NUM_MINUS",
                x_offset: 22.0,
                width: 1.0,
                height: 1.0,
            },
        ],
        // Tab row, second row of nav cluster, second row of numpad
        vec![
            Key {
                name: "TAB",
                x_offset: 0.0,
                width: 1.5,
                height: 1.0,
            },
            Key {
                name: "Q",
                x_offset: 1.5,
                width: 1.0,
                height: 1.0,
            },
            Key {
                name: "W",
                x_offset: 2.5,
                width: 1.0,
                height: 1.0,
            },
            Key {
                name: "E",
                x_offset: 3.5,
                width: 1.0,
                height: 1.0,
            },
            Key {
                name: "R",
                x_offset: 4.5,
                width: 1.0,
                height: 1.0,
            },
            Key {
                name: "T",
                x_offset: 5.5,
                width: 1.0,
                height: 1.0,
            },
            Key {
                name: "Y",
                x_offset: 6.5,
                width: 1.0,
                height: 1.0,
            },
            Key {
                name: "U",
                x_offset: 7.5,
                width: 1.0,
                height: 1.0,
            },
            Key {
                name: "I",
                x_offset: 8.5,
                width: 1.0,
                height: 1.0,
            },
            Key {
                name: "O",
                x_offset: 9.5,
                width: 1.0,
                height: 1.0,
            },
            Key {
                name: "P",
                x_offset: 10.5,
                width: 1.0,
                height: 1.0,
            },
            Key {
                name: "LEFT_BRACKET",
                x_offset: 11.5,
                width: 1.0,
                height: 1.0,
            },
            Key {
                name: "RIGHT_BRACKET",
                x_offset: 12.5,
                width: 1.0,
                height: 1.0,
            },
            Key {
                name: "BACKSLASH",
                x_offset: 13.5,
                width: 1.5,
                height: 1.0,
            },
            Key {
                name: "DELETE",
                x_offset: 15.5,
                width: 1.0,
                height: 1.0,
            },
            Key {
                name: "END",
                x_offset: 16.5,
                width: 1.0,
                height: 1.0,
            },
            Key {
                name: "PAGE_DOWN",
                x_offset: 17.5,
                width: 1.0,
                height: 1.0,
            },
            Key {
                name: "NUM_7",
                x_offset: 19.0,
                width: 1.0,
                height: 1.0,
            },
            Key {
                name: "NUM_8",
                x_offset: 20.0,
                width: 1.0,
                height: 1.0,
            },
            Key {
                name: "NUM_9",
                x_offset: 21.0,
                width: 1.0,
                height: 1.0,
            },
            Key {
                name: "NUM_PLUS",
                x_offset: 22.0,
                width: 1.0,
                height: 2.0,
            },
        ],
        // Caps Lock row, third row of numpad
        vec![
            Key {
                name: "CAPS_LOCK",
                x_offset: 0.0,
                width: 1.75,
                height: 1.0,
            },
            Key {
                name: "A",
                x_offset: 1.75,
                width: 1.0,
                height: 1.0,
            },
            Key {
                name: "S",
                x_offset: 2.75,
                width: 1.0,
                height: 1.0,
            },
            Key {
                name: "D",
                x_offset: 3.75,
                width: 1.0,
                height: 1.0,
            },
            Key {
                name: "F",
                x_offset: 4.75,
                width: 1.0,
                height: 1.0,
            },
            Key {
                name: "G",
                x_offset: 5.75,
                width: 1.0,
                height: 1.0,
            },
            Key {
                name: "H",
                x_offset: 6.75,
                width: 1.0,
                height: 1.0,
            },
            Key {
                name: "J",
                x_offset: 7.75,
                width: 1.0,
                height: 1.0,
            },
            Key {
                name: "K",
                x_offset: 8.75,
                width: 1.0,
                height: 1.0,
            },
            Key {
                name: "L",
                x_offset: 9.75,
                width: 1.0,
                height: 1.0,
            },
            Key {
                name: "SEMICOLON",
                x_offset: 10.75,
                width: 1.0,
                height: 1.0,
            },
            Key {
                name: "QUOTE",
                x_offset: 11.75,
                width: 1.0,
                height: 1.0,
            },
            Key {
                name: "ENTER",
                x_offset: 12.75,
                width: 2.25,
                height: 1.0,
            },
            Key {
                name: "NUM_4",
                x_offset: 19.0,
                width: 1.0,
                height: 1.0,
            },
            Key {
                name: "NUM_5",
                x_offset: 20.0,
                width: 1.0,
                height: 1.0,
            },
            Key {
                name: "NUM_6",
                x_offset: 21.0,
                width: 1.0,
                height: 1.0,
            },
        ],
        // Shift row, fourth row of numpad
        vec![
            Key {
                name: "LEFT_SHIFT",
                x_offset: 0.0,
                width: 2.25,
                height: 1.0,
            },
            Key {
                name: "Z",
                x_offset: 2.25,
                width: 1.0,
                height: 1.0,
            },
            Key {
                name: "X",
                x_offset: 3.25,
                width: 1.0,
                height: 1.0,
            },
            Key {
                name: "C",
                x_offset: 4.25,
                width: 1.0,
                height: 1.0,
            },
            Key {
                name: "V",
                x_offset: 5.25,
                width: 1.0,
                height: 1.0,
            },
            Key {
                name: "B",
                x_offset: 6.25,
                width: 1.0,
                height: 1.0,
            },
            Key {
                name: "N",
                x_offset: 7.25,
                width: 1.0,
                height: 1.0,
            },
            Key {
                name: "M",
                x_offset: 8.25,
                width: 1.0,
                height: 1.0,
            },
            Key {
                name: "COMMA",
                x_offset: 9.25,
                width: 1.0,
                height: 1.0,
            },
            Key {
                name: "PERIOD",
                x_offset: 10.25,
                width: 1.0,
                height: 1.0,
            },
            Key {
                name: "SLASH",
                x_offset: 11.25,
                width: 1.0,
                height: 1.0,
            },
            Key {
                name: "RIGHT_SHIFT",
                x_offset: 12.25,
                width: 2.75,
                height: 1.0,
            },
            Key {
                name: "UP_ARROW",
                x_offset: 16.5,
                width: 1.0,
                height: 1.0,
            },
            Key {
                name: "NUM_1",
                x_offset: 19.0,
                width: 1.0,
                height: 1.0,
            },
            Key {
                name: "NUM_2",
                x_offset: 20.0,
                width: 1.0,
                height: 1.0,
            },
            Key {
                name: "NUM_3",
                x_offset: 21.0,
                width: 1.0,
                height: 1.0,
            },
            Key {
                name: "NUM_ENTER",
                x_offset: 22.0,
                width: 1.0,
                height: 2.0,
            },
        ],
        // Control row, last row of numpad
        vec![
            Key {
                name: "LEFT_CTRL",
                x_offset: 0.0,
                width: 1.25,
                height: 1.0,
            },
            Key {
                name: "LEFT_WIN",
                x_offset: 1.25,
                width: 1.25,
                height: 1.0,
            },
            Key {
                name: "LEFT_ALT",
                x_offset: 2.5,
                width: 1.25,
                height: 1.0,
            },
            Key {
                name: "SPACE",
                x_offset: 3.75,
                width: 6.25,
                height: 1.0,
            },
            Key {
                name: "RIGHT_ALT",
                x_offset: 10.0,
                width: 1.25,
                height: 1.0,
            },
            Key {
                name: "RIGHT_WIN",
                x_offset: 11.25,
                width: 1.25,
                height: 1.0,
            },
            Key {
                name: "MENU",
                x_offset: 12.5,
                width: 1.25,
                height: 1.0,
            },
            Key {
                name: "RIGHT_CTRL",
                x_offset: 13.75,
                width: 1.25,
                height: 1.0,
            },
            Key {
                name: "LEFT_ARROW",
                x_offset: 15.5,
                width: 1.0,
                height: 1.0,
            },
            Key {
                name: "DOWN_ARROW",
                x_offset: 16.5,
                width: 1.0,
                height: 1.0,
            },
            Key {
                name: "RIGHT_ARROW",
                x_offset: 17.5,
                width: 1.0,
                height: 1.0,
            },
            Key {
                name: "NUM_0",
                x_offset: 19.0,
                width: 2.0,
                height: 1.0,
            },
            Key {
                name: "NUM_PERIOD",
                x_offset: 21.0,
                width: 1.0,
                height: 1.0,
            },
        ],
    ]
});

const KEY_ROTATION: phf::Map<&'static str, f32> = phf_map! {
    "UP_ARROW" => -PI / 2.,
    "W" => -PI / 2.,
    "LEFT_ARROW" => -PI,
    "A" => -PI,
    "DOWN_ARROW" => PI / 2.,
    "S" => PI / 2.,
    "RIGHT_ARROW" => 0.,
    "D" => 0.,
};

const INPUTS: phf::Map<&str, [&str; 2]> = phf_map! {
    "up" => ["UP_ARROW", "W"],
    "left" => ["LEFT_ARROW", "A"],
    "down" => ["DOWN_ARROW", "S"],
    "right" => ["RIGHT_ARROW", "D"],
};

#[derive(GodotClass)]
#[class(base=Control)]
pub struct KeymapDisplay {
    keys: HashMap<&'static str, Gd<Control>>,

    base: Base<Control>,
}

#[godot_api]
impl KeymapDisplay {
    fn set_keys_color(&mut self, action: &'static str, color: Color) {
        for key in INPUTS.get(action).unwrap() {
            self.keys.entry(key).and_modify(|k| k.set_modulate(color));
        }
        self.base()
            .get_parent()
            .unwrap()
            .get_node_as::<BoxContainer>(format!("ExplainContainer/{action}Container"))
            .set_modulate(color);
        self.base()
            .get_parent()
            .unwrap()
            .get_node_as::<Control>(format!("Controller/{action}"))
            .set_modulate(color);
    }
}

#[godot_api]
impl IControl for KeymapDisplay {
    fn init(base: Base<Control>) -> Self {
        KeymapDisplay {
            keys: HashMap::new(),
            base,
        }
    }

    fn ready(&mut self) {
        let key_scene: Gd<PackedScene> = load("res://scenes/ui/key.tscn");

        for (y, line) in KEYMAP.iter().enumerate() {
            for key in line.iter() {
                let mut key_instance = key_scene.instantiate_as::<Control>();
                let key_size = key_instance.get_size();
                let key_size_with_border = key_size;
                key_instance.set_position(Vector2::new(
                    key_size_with_border.x * key.x_offset,
                    key_size_with_border.y * y as f32,
                ));
                key_instance.set_size(key_size * Vector2::new(key.width, key.height));

                match KEY_ROTATION.get_entry(key.name) {
                    Some((_, rotation)) => key_instance.set_rotation(*rotation),
                    None => {
                        key_instance
                            .get_node_as::<BoxContainer>("ArrowContainer")
                            .hide();
                    }
                }

                self.base_mut().add_child(key_instance.clone().upcast());
                self.keys.insert(key.name, key_instance);
            }
        }
    }

    fn input(&mut self, event: Gd<InputEvent>) {
        for &action in INPUTS.keys() {
            if event.is_action_pressed(action.into()) {
                self.set_keys_color(action, COLOR_SUCCESS);
            } else if event.is_action_released(action.into()) {
                self.set_keys_color(action, COLOR_FOREGROUND);
            }
        }
    }
}
